In [1]:
import os
from __future__ import print_function
from numpy import array
from IPython.display import Image
PATH = os.getcwd()

# ANACONDA INSTALLATION

# https://docs.anaconda.com/anaconda/install/

![python](https://mfr.osf.io/export?url=https://osf.io/3xzd5/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+python1.png&parentUrl=https://osf.io/3xzd5/&format=2400x2400.jpeg)

![disclaimer](https://mfr.osf.io/export?url=https://osf.io/u25vq/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+disclaimer.png&parentUrl=https://osf.io/u25vq/&format=2400x2400.jpeg)

![data](https://mfr.osf.io/export?url=https://osf.io/xzsny/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+data_types.png&parentUrl=https://osf.io/xzsny/&format=2400x2400.jpeg)

# **PRIMATIVES**

## Integers, Floats, Strings, and Booleans

### Integers are values represented as whole numbers

In [2]:
int1 = 1 #whole number

print(type(int1)) # The type() function allows us to the data type of a variable

<type 'int'>


### Floats are values represented as decimals

In [3]:
float1 = 1.0 #decimal number

print(type(float1))

<type 'float'>


### Strings are sequences of characters -- letters, numbers, and/or symbols

In [4]:
string1 = 'hello_world' #characters in quotes

print(type(string1))

<type 'str'>


### Boolean values are binary, representing "True" and "False"

In [5]:
value1 = True
value2 = False

print(type(value1))
print(type(value2))

# Booleans are most often used in conditional statements or while loops to indicate when a process should begin or end

<type 'bool'>
<type 'bool'>


# -----------------------------------------------------------------------------

# **NON-PRIMATIVES**

# *-- LISTS VS ARRAYS: SIMILARITIES & DIFFERENCES --*

## - LISTS -

* Variables containing an ordered group of elements

In [6]:
list1 = [1,2,3,4,5,6,7,8]
list1.append(10) #add 10 to the end of the list
print('It can change!', list1)

It can change! [1, 2, 3, 4, 5, 6, 7, 8, 10]


### Indexable 
* Can be used to isolate specific values

![index](https://qph.fs.quoracdn.net/main-qimg-a380b1bc159589df5e0b9842e5b56b6d)

In [7]:
list2 = [1,2,3,4,5,6,7,8]

item1 = list2[3]
item2 = list2[-5]

print('Select the same item in list2', item1, item2)

Select the same item in list2 4 4


### Sliceable
* Multiple values within a list can be selected

In [8]:
list3 = [1,2,3,4,5,6,7,8]

slice_list3 = list3[2:-2] #use both types of index methods to grab list values 3 - 6
print('Select multiple specific values', slice_list3)

Select multiple specific values [3, 4, 5, 6]


### Iterable
* Using a loop, individual values can be used 1 (or more) at a time


In [9]:
list4 = [1,2,3,4,5,6,7,8]

for i in list4:
    print(i)

1
2
3
4
5
6
7
8


### Lists _do not_ allow arithmetic operations on elements

* If one tries, the following error will be returned:

In [10]:
list4 = [1,2,3,4,5,6,7,8]

list4_half = list4/2.

TypeError: unsupported operand type(s) for /: 'list' and 'float'

## - ARRAYS -

### Allow you to do everything as with lists, BUT ALSO MATH!! 

In [11]:
array1 = array([1,2,3,4,5,6,7,8]) #array method surrounds the bracketed list, converting into an array

divided_array = array1/2.
print('We can divide!', divided_array)

multiplied_array = array1*2.
print('We can multiply!', multiplied_array)

We can divide! [ 0.5  1.   1.5  2.   2.5  3.   3.5  4. ]
We can multiply! [  2.   4.   6.   8.  10.  12.  14.  16.]


### You can get as complicated as necessary...

In [12]:
complex_array = array1*2/10. # Make sure to remember PEMDAS!

print(complex_array)

[ 0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6]


### ...but think carefully about the _structure_ of your data and how you _manipulate_ it.

In [13]:
array1 = array([1,2,3,4,5,6,7,8]) # these values are integers

complex_array = array1*2/10 # the values you are using to change the array are integers too
print("This doesn't seem right...", complex_array)

This doesn't seem right... [0 0 0 0 1 1 1 1]


### There's two easy ways to fix this...

#1. Add a decimal to any of number used to change the array values
#2. Use the float() method to convert the numerator/denominator to a float

In [14]:
# Add a decimal
complex_array1 = array1*2/10.
print('Adding a decimal works!', complex_array1)

# Convert using float function
complex_array2 = array1*2/float(10)
print('Float method works too!', complex_array2)

Adding a decimal works! [ 0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6]
Float method works too! [ 0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6]


## - TUPLES -

### Tuples are collections of objects separated by commas, with or without parentheses
* Lists are difference because the contents are surrounded by squarre brackets
* Arrays have square brackets AND array()

In [15]:
tuple1 = ('item1', 'item2') 
tuple2 = 'item1', 'item2'

list1 = ['item1', 'item2'] 
array1 = array(['item1', 'item2']) 

print(type(tuple1))
print(type(tuple2))
print(type(list1))
print(type(array1))

<type 'tuple'>
<type 'tuple'>
<type 'list'>
<type 'numpy.ndarray'>


### Tuples cannot be changed, unlike lists and arrays
* Multiply with parentheses at creation
* Cannot append new values

In [16]:
list1 = [1,2,3,4,5,6,7,8]
list1.append(10)
print(list1)

tuple1 = ('python',)*3
print(type(tuple1))
print(tuple1)

tuple2 = (1,2,3,4,5,6,7,8)
tuple2.append(10) 

[1, 2, 3, 4, 5, 6, 7, 8, 10]
<type 'tuple'>
('python', 'python', 'python')


AttributeError: 'tuple' object has no attribute 'append'

### Tuples can be added together

In [17]:
tuple1 = (1,2,3,4)
tuple2 = ('A','B','C','D')
new_mixed_object = tuple1 + tuple2
print(new_mixed_object)

(1, 2, 3, 4, 'A', 'B', 'C', 'D')


# -- DICTIONARIES --

### Create a dictionary using curly brackets, keys, and values in square brackets

In [18]:
dict1 = {'key1':[1,2,3,4,5], 'key2':[6,7,8,9,10], 'key3':[11,12,13,14,15]}

print(type(dict1))
print(dict1)

<type 'dict'>
{'key3': [11, 12, 13, 14, 15], 'key2': [6, 7, 8, 9, 10], 'key1': [1, 2, 3, 4, 5]}


### Dictionaries are *not* naturally ordered
* Ordered dictionaries can be created using the OrderedDict()

In [19]:
from collections import OrderedDict 

dict1 = {'key1':[1,2,3,4,5], 'key2':[6,7,8,9,10], 'key3':[11,12,13,14,15]}

keys = ['key1', 'key2', 'key3']
list_of_tuples = [(key, dict1[key]) for key in keys] #list comprehension is awesome!!
ordered_dict = OrderedDict(list_of_tuples)
print(ordered_dict)

OrderedDict([('key1', [1, 2, 3, 4, 5]), ('key2', [6, 7, 8, 9, 10]), ('key3', [11, 12, 13, 14, 15])])


### Values can be accessed and/or changed by referencing the key

In [20]:
print('original', ordered_dict['key1'])

ordered_dict['key1'] = [21,22,23,24,25]
print('edited', ordered_dict['key1'])

original [1, 2, 3, 4, 5]
edited [21, 22, 23, 24, 25]


### Specific items can be changed by referencing key and/or index

In [21]:
print('complete key-value', ordered_dict['key2'])

print('first item in key2', ordered_dict['key2'][0])
print('first 4 items in key2', ordered_dict['key2'][0:4]) #you can slice just like lists and arrays!

complete key-value [6, 7, 8, 9, 10]
first item in key2 6
first 4 items in key2 [6, 7, 8, 9]


### New key-value pairs can be added to an existing dictionary

In [22]:
dict2 = {'key1':[1,2,3,4,5], 'key2':[6,7,8,9,10], 'key3':[11,12,13,14,15]}
dict2['key4'] = [16,17,18,19,20]

print(dict2)

## If you add a new key-value pair to an ordered dictionary, it will be appended to the end and NOT ordered

{'key3': [11, 12, 13, 14, 15], 'key2': [6, 7, 8, 9, 10], 'key1': [1, 2, 3, 4, 5], 'key4': [16, 17, 18, 19, 20]}


### You can remove key-value pairs using the .pop method

In [23]:
dict2 = {'key1':[1,2,3,4,5], 'key2':[6,7,8,9,10], 'key3':[11,12,13,14,15]}

print('original dict2', dict2)
dict2.pop('key2')
print('removing key2', dict2)

original dict2 {'key3': [11, 12, 13, 14, 15], 'key2': [6, 7, 8, 9, 10], 'key1': [1, 2, 3, 4, 5]}
removing key2 {'key3': [11, 12, 13, 14, 15], 'key1': [1, 2, 3, 4, 5]}


# -----------------------------------------------------------------------------

# PYTHON STATEMENT, INDENTATION, & COMMENTS
* Before learning about loops, we need to understand how Python handles statements, blocks of code, and indentation

In [24]:
# Simple assignment statement
variable = 1

print(variable)

1


### Multi-line statements, line breaks, and line continuation
* Back slashes serve to break long lines of code into more readable pieces 
* a, b, and c return the same value

In [25]:
# Single line format
a = 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9

# Line break format
b = 1 + 2 + 3 + \
    4 + 5 + 6 + \
    7 + 8 + 9
    
# Line continuation
c = (1 + 2 + 3 + 4 + 5 
     + 6 + 7 + 8 + 9)
    
print(a)
print(b)
print(c)

45
45
45


### How Python identifies blocks of code
* Other languages, such as C++ and Java, use curly brackets to define blocks of code
* Python uses indentation to organize code into coherent statements

### A block of code typically begins with a loop, conditional statment, or function definition
* Everything indented below the first line is interpreted as belonging to the same block of code
* Indentations are 4 spaces (or one tab) from the preceding line
* Indented code below is executed each time the for loop runs

In [26]:
for num in range(1,11): 
    print(num) #four spaces from for loop
    if num == 5:
        break #four spaces from if statement

1
2
3
4
5


### Comments
* Comments are **life-savers** and the greatest gift you can give to your future selves
## Comment _EVERYTHING_

<img src="https://mfr.osf.io/export?url=https://osf.io/dvucw/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+comments.png&parentUrl=https://osf.io/dvucw/&format=2400x2400.jpeg"
     alt="commenting"
     style="float: left; width: 400px" />

### Use # at the beginning of a new line to write a comment
### You can also add a comment using # at the end of a line of code

In [27]:
#loops through all colors and suits

print(list1) #prints all values contained in list1

[1, 2, 3, 4, 5, 6, 7, 8, 10]


### Multi-line comments
* If your comments are longer than a single line, you can easily break them into multiple lines using multiple # or three single quotes (''' ''') or three double quotes (""" """)

In [28]:
#According to all known laws of aviation, there is no way a bee should be able to fly. 
#Its wings are too small to get its fat little body off the ground.
#The bee, of course, flies anyway because bees don't care what humans think is impossible. 
#Yellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Let's shake it up a little.

'''
According to all known laws of aviation, there is no way a bee should be able to fly. 
Its wings are too small to get its fat little body off the ground.
The bee, of course, flies anyway because bees don't care what humans think is impossible. 
Yellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Let's shake it up a little.
'''

"\nAccording to all known laws of aviation, there is no way a bee should be able to fly. \nIts wings are too small to get its fat little body off the ground.\nThe bee, of course, flies anyway because bees don't care what humans think is impossible. \nYellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Let's shake it up a little.\n"

# -----------------------------------------------------------------------------

# LOOPS

## -- FOR LOOPS --
* Allows code to iterate (repeat) over a sequence (list, tuple, dictionary, string, etc)

### Simple for loop over a list of strings

In [29]:
fruits = ["apple", "banana", "cherry"]
for this_fruit in fruits:
    print(this_fruit)

apple
banana
cherry


### Simple for loop over the letters in a string

In [30]:
for letter in "banana":
    print(letter)

b
a
n
a
n
a


### Breaking for loops
* Stop the loop before it has completed the list

In [31]:
fruits = ["apple", "banana", "cherry"]
for this_fruit in fruits:
    print(this_fruit) 
    if this_fruit == "banana":
        break

apple
banana


### Continuing for loops
* Stop a current iteration and continue to the next element in the list

In [32]:
fruits = ["apple", "banana", "cherry"]
for this_fruit in fruits:
    if this_fruit == "banana":
        continue
    print(this_fruit)

apple
cherry


### Nested for loops
* Iteration through multiple lists
* Loops 10 times (number of teams X number of mains)

In [33]:
teams = ['Red', 'Blue']
mains = ['Heavy', 'Spy', 'Scout', 'Medic', 'Pyro']

for this_team in teams:
    for this_main in mains:
        print(this_team, this_main)

Red Heavy
Red Spy
Red Scout
Red Medic
Red Pyro
Blue Heavy
Blue Spy
Blue Scout
Blue Medic
Blue Pyro


### Enumeration of elements
* Provides the index of the current item in the iteration (i.e. this_main)
* Kinda like counting the number of times the loop iterates (starting at 0)

In [35]:
mains = ['Heavy', 'Spy', 'Scout', 'Medic', 'Pyro']

for i, this_main in enumerate(mains):
    print(i+1, this_main) #if 1 is added to i, it's just like counting!

1 Heavy
2 Spy
3 Scout
4 Medic
5 Pyro


## -- WHILE LOOPS --

* Allows code to iterate (repeat) until a particular condition is met
* Good for when the number of necessary iterations is unknown
    * Counters and/or booleans are usually needed

### Simple while loop with counter condition

In [36]:
counter = 0

while counter < 5:
    print(counter)
    counter += 1  

0
1
2
3
4


### Simple while loop with counter AND boolean

In [37]:
boolean = True
counter = 0

while boolean == True: #equivalent test
    counter +=1
    print(boolean)
    if counter == 3:
        boolean = False #reassignment
        print(boolean)

True
True
True
False


### Breaking while loops
* Terminate the while loop using **break**

In [38]:
counter = 1
while True: # it would go forever!
    print(counter)
    if counter == 3:
        break # terminate once counter reaches 3
    counter += 1  

1
2
3


### Continuing while loops
* Stop the current iteration and continue to the next

In [39]:
counter = 0
while counter < 6:
    counter += 1 
    if counter == 3:
        continue #continue after counter reaches 3
    print(counter)

1
2
4
5
6


## -- FROOT LOOPS --
* Just tastes good

![frooooooot](https://mfr.osf.io/export?url=https://osf.io/a7zrj/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+froot_loops.png&parentUrl=https://osf.io/a7zrj/&format=2400x2400.jpeg)

# CONDITIONAL STATEMENTS

## Comparison Operators
* Operators that allow conditional statements to compare values

![comp ops](https://mfr.osf.io/export?url=https://osf.io/pxcqb/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+comparison_ops.png&parentUrl=https://osf.io/pxcqb/&format=2400x2400.jpeg)

## -- IF, ELIF, AND ELSE --

In [40]:
grade = 90
letter = ""

if grade >= 90:
    letter = "A"
elif grade >= 80:
    letter = "B"
elif grade >= 70:
    letter = "C"
elif grade >= 60:
    letter = "D"
else:
    letter = "F"
    
print(letter)

A


### Using conditional statements in a loop

In [41]:
class_grades = [75, 77, 56, 97, 87, 67, 92, 73, 88, 95]
class_letters = []

for grade in class_grades:
    if grade >= 90:
        letter = "A"
    elif grade >= 80:
        letter = "B"
    elif grade >= 70:
        letter = "C"
    elif grade >= 60:
        letter = "D"
    else:
        letter = "F"
    class_letters.append(letter)
print(class_letters)

['C', 'C', 'F', 'A', 'B', 'D', 'A', 'C', 'B', 'A']


# -----------------------------------------------------------------------------

# ADDRESSING EXCEPTIONS (ERRORS)

![error types](https://mfr.osf.io/export?url=https://osf.io/mwvdf/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+error_types.png&parentUrl=https://osf.io/mwvdf/&format=2400x2400.jpeg)

# -----------------------------------------------------------------------------

# BEGINNER EXERCISE

### Write a short script to create a list containing all friendly mobs, then print it!


In [42]:
mobs = ['creepers', 'wolf', 'cat', 'zombie', 'skeleton', 'dolphin']
behavior = [0,1,1,0,0,1] # 0 = hostile, 1 = friendly

<img src="https://mfr.osf.io/export?url=https://osf.io/nhcem/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+arithmetic_ops.png&parentUrl=https://osf.io/nhcem/&format=2400x2400.jpeg"
     alt="commenting"
     style="float: left; width: 700px" />

<img src="https://mfr.osf.io/export?url=https://osf.io/pnurq/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+logical_ops.png&parentUrl=https://osf.io/pnurq/&format=2400x2400.jpeg"
     alt="commenting"
     style="float: left; width: 600px" />

# -----------------------------------------------------------------------------

![imports pic](https://mfr.osf.io/export?url=https://osf.io/4mj5c/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+imports.png&parentUrl=https://osf.io/4mj5c/&format=2400x2400.jpeg) 

# NumPy 
## Library for scientific computing in Python
## https://www.numpy.org

### NumPy - IMPORTING - 

In [43]:
import numpy #general importing
import numpy as np # alias importing

### NumPy - IMPORTING SPECIFIC PACKAGES AND/OR TOOLS - 

In [44]:
from numpy import random #import the entire random package

print(1, numpy.random.random())
print(2, np.random.random())
print(3, random.random())

from numpy.random import random #import only the specific random function within the random package
print(4, random())

1 0.219135280115
2 0.835939467275
3 0.624818276342
4 0.340759566989


## NumPy arrays are your friends
* Allows simultaneous mathematical computations on the elements of an array
* Easily reshapeable
* Easily searchable
* Gotta go _fast_

In [45]:
D1_array = np.array([1, 2, 3]) #1D array
print(type(D1_array))  
print(D1_array.shape)

<type 'numpy.ndarray'>
(3,)


In [46]:
D2_array = np.array([[1,2,3],
                     [4,5,6]]) #2D array
print(D2_array.shape)
print(D2_array[0, 0], D2_array[0, 1], D2_array[1, 0])

(2, 3)
1 2 4


### Searching arrays using np.where()
* Make a random 4x4 array and find all values greater than 0.5
* Create variable to contain all indices in array1 greater than 0.5
* Print greater_05 to review elements

In [47]:
array1 = random(size=(4,4))
print("initial random array \n", array1)
print("")
greater_05 = np.where(array1 > .5)
print("indices for elements > 0.5 \n", np.vstack(greater_05).T)
print("")
print("elements > 0.5 \n", array1[greater_05])

initial random array 
 [[ 0.63572496  0.6354901   0.32431798  0.83534734]
 [ 0.45645657  0.91749843  0.99906621  0.30198341]
 [ 0.27494496  0.47969581  0.33174023  0.72699435]
 [ 0.83362422  0.59494386  0.64128998  0.341547  ]]

indices for elements > 0.5 
 [[0 0]
 [0 1]
 [0 3]
 [1 1]
 [1 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]]

elements > 0.5 
 [ 0.63572496  0.6354901   0.83534734  0.91749843  0.99906621  0.72699435
  0.83362422  0.59494386  0.64128998]


![numpy example](https://mfr.osf.io/export?url=https://osf.io/xundr/?action=download%26mode=render%26direct%26public_file=True&initialWidth=684&childId=mfrIframe&parentTitle=OSF+%7C+np_indexing.png&parentUrl=https://osf.io/xundr/&format=2400x2400.jpeg)

## NumPy provides functions to create populated arrays

In [48]:
zeros_array = np.zeros((2,3)) # Create an array of all zeros
print(zeros_array)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [49]:
ones_array = np.ones((2,3))  # Create an array of all ones
print(ones_array)  

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [50]:
full_array = np.full((2,3), 7)  # Create a constant array
print(full_array) 

[[ 7.  7.  7.]
 [ 7.  7.  7.]]


//anaconda/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 3), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [51]:
random_array = np.random.random((2,3))  # Create an array filled with random values
print(random_array)                     

[[ 0.16724674  0.14919649  0.78755811]
 [ 0.5626943   0.11102855  0.08762335]]


# SciPy Stats
## Even more math than NumPy! Fresh new inferential analyses!
## https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html

In [52]:
import scipy.stats as stats

# pandas -- Python Data Analysis Library
## Dictionaries with all the mathematical functionality of NumPy!
## https://pandas.pydata.org/pandas-docs/stable/reference/index.html

In [53]:
import pandas as pd